name: Upload Python Package and Build Lambda Layer

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Run tests
      run: |
        pip install -e .
        python -m unittest discover tests "test_*.py" -v

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  build-lambda-layer:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv

    - name: Create Lambda Layer
      run: |
        virtualenv venv
        source venv/bin/activate
        mkdir python
        PACKAGE_VERSION=$(python setup.py --version)
        echo "fear-and-greed-crypto==$PACKAGE_VERSION" > requirements.txt
        docker run --rm -v "$PWD":/var/task public.ecr.aws/sam/build-python3.12:latest /bin/sh -c "pip install --platform manylinux2014_x86_64 --implementation cp --python 3.12 --only-binary=:all: --upgrade -r requirements.txt -t python"
        zip -r layer-python3.12-x86_64.zip python

    - name: Upload Layer to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./layer-python3.12-x86_64.zip
        asset_name: layer-python3.12-x86_64.zip
        asset_content_type: application/zip
